spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/eam?characterEncoding=utf-8&useSSL=false
#    username: kmbx
#    password: Qw594906790
#    url: jdbc:mysql://119.23.102.176:3306/bxsj?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: true

server:
  servlet:
    path: /csxm #打成war包部署到服务器时注销此行

mybatis:
  mapper-locations: classpath:mapper/**/*.xml